### PR TITLE
Implement tab views

### LINKED ISSUE #70: [Shortcode] Tabs
Hello,

Please add horizontal tabs. This feature is useful for an API documentation to give code sample for multiple languages (ex: Shell, Python, Java, ...)

image

### PR DESCRIPTION
**Pull request by swenzel**
We recently decided to add this to our internal documentation. I thought other people might find it useful, too. 
I do speak some French but I'd still leave the translation up to someone else.

closes #70 

Btw. the code was inspired by solutions from:
https://github.com/gohugoio/hugoDocs/
https://github.com/kubernetes/website/
https://www.mediaevent.de/tutorial/css-tabs.html

### CODE REVIEW

**Comment by matalo33** [comment]
Love it! Thanks so much for your contribution. I'd like to get 2.5 shipped as it already contains several improvements and bug fixes. This will be properly reviewed and merged asap after it.

If you didn't see already, the live demo looks fantastic https://deploy-preview-386--learn.netlify.com/en/shortcodes/tabs/

**Comment by johnDorian** [comment]
Just tried this out locally using hugo v0.74.3, but it wasn't working. It seems this bug was fixed by #403.

**Comment by fritzmg** [comment]
Any update on this? Would be great to have in the Hugo Learn Theme :)

**Comment by MichaelStott** [comment]
Same here, can this be merged or is there anything still pending?

**Comment by gadams999** [comment]
This is awesome and just what I needed to reduce page lengths. What's the normal time frames for PR inclusion into the learn theme?

**Pull request merged**
