### PR TITLE
Upgrade mermaid-js/mermaid @ 0918b97 (v8.8.0)

### PR DESCRIPTION
**Pull request by mbbx6spp**
I upgraded the mermaid-js/mermaid static JS with the minimized version built by using the following method:

```bash
$ wget -q https://github.com/mermaid-js/mermaid/archive/8.8.0.zip
...
$ unzip mermaid-8.8.0.zip
$ cd mermaid-8.8.0/

$ nix-shell -p yarn --run "yarn install && yarn release" # equivalent to 'yarn install && yarn release' if yarn already installed
...

$ shasum -a 256 <./dist/mermaid.min.js
d27383a9754a526f5e46d6f39d0c17cdb66bbd2bf5285242e8abdf841831a2ec  -
```

The new mermaid has support for a lot more diagram types including:
- `stateDiagram-v2`: state diagram
- `erDiagram`: entity-relationship diagram
- `journey`: user journey

More information here: https://mermaid-js.github.io/mermaid/diagrams-and-syntax-and-examples/n00b-syntaxReference.html

This PR also includes changes to the `exampleSite` that fix formatting in the mermaid shortcode examples for correct rendering and adds a new example for the `stateDiagram-v2` for both English and French (please make suggestions to my French state machine for more appropriate words).

### CODE REVIEW

**Comment by mbbx6spp** [comment]
BTW I love this Learn theme! Thank you.

**Comment by mbbx6spp** [comment]
This is explicitly not trying to solve the CDN issue mentioned in other issues. It is the dumbest upgrade path so that the Learn theme can support a newer mermaid sooner since all the other CDN resolving PRs did not get merged so far.

**Comment by matalo33** [comment]
Thanks @mbbx6spp, let's get this merged while larger CDN discussion takes place. Also thanks for providing me steps to validate the contents of the javascript you provided, however I have mismatching sha256 on my side during validation.

Could I ask why you do a yarn build when the zip file already contains the minified js?

My steps to validate as follows...

```
$ curl -LO https://github.com/mermaid-js/mermaid/archive/8.8.0.zip
$ unzip 8.8.0.zip
$ shasum -a 256 mermaid-8.8.0/dist/mermaid.min.js
d373ecc0e80fed423a6ee72fe30f4307aad5a04d872fa14e98ff3f2e8be4aae0  mermaid-8.8.0/dist/mermaid.min.js
```

**Comment by mbbx6spp** [comment]
@matalo33 should be fixed now. The SHA256 of the file in the repo at `static/mermaid/mermaid.js` should now match your SHA.

**Comment by matalo33** [comment]
Excellent thanks very much!

I confirm `d373ecc0e80fed423a6ee72fe30f4307aad5a04d872fa14e98ff3f2e8be4aae0` from `dist/mermaid.min.js` in `https://github.com/mermaid-js/mermaid/archive/8.8.0.zip`

**Comment by McShelby** [comment]
Sadly, there are issues with mermaid 8.8.0 and versions prior itself.

- Since version 8.2.0, click events and HTML inside of mermaid graphs are only working if `securityLevel="loose"` is set during `mermaid.initialize`. [See here](https://mermaid-js.github.io/mermaid/getting-started/usage.html?highlight=securityLevel#to-enable-click-event-and-tags-in-nodes).

  Since mermaid 8.7.0 there is a `securityLevel="antiscript"` that seems to be a good fit for a default configuration in our theme.
- Since mermaid 8.7.0, `mermaid.initialize` does not carry over its initialized values to a rendered graph. If `securityLevel="loose"` ist set during our initialization code in `footer.html` this will not be applied during rendering.

  The official [mermaid docs may suffer form the same issue](https://mermaid-js.github.io/mermaid/diagrams-and-syntax-and-examples/flowchart.html#css-classes). The `<span>` tag is renderd as text.

- The mermaid 8.2.x branch suffers from incorrect padding for some nodes.

I tested **mermaid 8.6.4** and all the above issues are not observable there. So that's my current favorite until further issues.

**Comment by mirisbowring** [comment]
Probably we should add a param to enable / disable your mentioned "fix" and document it on the configuration page.

Since the CDN PR was merged, Users of the CDN will also profit from the toggle fix.

If we just downgrade, users with a later version are still having this Problem.

**Comment by McShelby** [comment]
I would prefer to have the whole mermaid config object to be configurable from our `config.toml`. This would allow users to set further ***secure*** mermaid options, that are only settable once during intialization.

This would also allow users to set the mermaid theme, which was requested in #435

I will open another issue and a PR for this.

**Pull request merged**
