### PR TITLE
fix parsed markdown not being processed

### PR DESCRIPTION
**Pull request by inwardmovement**

### CODE REVIEW

**Comment by inwardmovement** [comment]
Hi @matcornic Mathieu, could you merge so I can delete my fork?

**Comment by matalo33** [comment]
This prevents any and all notices being displayed on the examplesite. What is it trying to achieve exactly?

**Comment by inwardmovement** [comment]
The notices weren't processing markdown that's why I made this PR to correct that, but it may not be relevant any more since then, I close the PR and delete the fork.

**Comment by matalo33** [comment]
Okay, I understand what you mean now. When I tested the branch however it was preventing all notices being displayed at all. If you'd like to re-submit something I'll happily have a look.

**Pull request closed without merging**
