### PR TITLE
This close #198

### LINKED ISSUE #198: Update mermaid to latest master version in order to enable class diagrams
Class diagrams are not working well with the mermaid version included with the theme. Please, update to the latest master commit of mermaid to enable class diagrams.

### PR DESCRIPTION
**Pull request by massimeddu**
Please accept this pull request to close issue #198 .

Thank you,

### CODE REVIEW

**Comment by matalo33** [comment]
Please could you include where you sourced this file from? Ideally a git commit of the upstream repo. Thanks

**Comment by massimeddu** [comment]
Hi @matalo33, I just downloaded this commit:

https://github.com/knsv/mermaid/commit/a4992963b3873ec7a566ba91b92596d2a360e3b9

and then ran

yarn install
yarn release

then copied the dist/mermaid.min.js into static/mermaid/mermaid.js

Thank you

**Comment by massimeddu** [comment]
Hi @massimeddu , did you had the chance to review this change?

Please, let me know if you need more details.

Thank you,

**Comment by matalo33** [comment]
Thank you, verified this mermaid.js came from upstream `a499296`

**Pull request merged**
