### PR TITLE
Add Turkish i18n config file

### PR DESCRIPTION
**Pull request by 654wak654**
Made this lil' file for a project, figured I should send it upstream.

### CODE REVIEW

**Comment by matalo33** [comment]
@matcornic Do you know why the wecker build fails regularly? I don't have permissions to see the pipeline

**Comment by matcornic** [comment]
@matalo33 can you give me your username on Wercker so I can give you rights ?

The problem is because Hugo does not compile, probably because [Golang env on Wercker is not in 1.11](github.com/gohugoio/hugo)

I use the latest version of Hugo to check if the theme is still working with latest version.

```
source "/pipeline/script-c9e8d70b-44f7-4995-8acb-e8833497f6c1/run.sh" < /dev/null
# github.com/gohugoio/hugo/hugolib
../../gohugoio/hugo/hugolib/hugo_sites.go:72:18: h.Deps.Log.LogCountForLevelsGreaterThanorEqualTo undefined (type *jwalterweatherman.Notepad has no field or method LogCountForLevelsGreaterThanorEqualTo)
../../gohugoio/hugo/hugolib/hugo_sites.go:304:7: h.Deps.Log.ResetLogCounters undefined (type *jwalterweatherman.Notepad has no field or method ResetLogCounters)
../../gohugoio/hugo/hugolib/hugo_sites_build.go:82:21: h.Deps.Log.LogCountForLevel undefined (type *jwalterweatherman.Notepad has no field or method LogCountForLevel)
```

**Comment by matalo33** [comment]
> @matalo33 can you give me your username on Wercker so I can give you rights ?

Thanks, just signed up, `matalo33`

**Comment by matcornic** [comment]
> > @matalo33 can you give me your username on Wercker so I can give you rights ?
> 
> Thanks, just signed up, `matalo33`

Added you

**Comment by matcornic** [comment]
You can sign up on Netlify too for deployment

**Comment by matalo33** [comment]
> Added you. Btw, you have a twitter or something (so we can avoid flooding issues with short messages) ?

Good idea, I was thinking of how to better have discussions, twitter works :). `matt____taylor`

**Pull request merged**
