### PR TITLE
supporting a base url that is not the root of a domain

### PR DESCRIPTION
**Pull request by nimmaj**
Hey - awesome theme - thanks.  I found i had to do the following in order to allow me to deploy the site underneath http://my.domain.com/subdir/  - otherwise the theme looked in http://my.domain.com/css for the css for example rather than http://my.domain.dom/subdir/css/ - wondered whether you wanted to add this to the theme?  Thanks.

### CODE REVIEW

**Comment by matcornic** [comment]
Hello Ben ! Thanks 😄
I think you may fix this by using the `canonifyURLs = true` property in your `config.toml`. See the discussion #3 and especially my last message.

Test it and get back to me to tell me if it's working or not ;).

**Comment by nimmaj** [comment]
Hey - thanks for that - should have seen that in the docs - you are quite right of course!  Apols for the daft pull request ;-)

Ben

**Comment by matcornic** [comment]
Don't worry, you're not the first (myself included) and you won't be the last, it's not that obvious ;)

**Comment by jehoshua7** [comment]
#https://github.com/matcornic/hugo-theme-learn/issues/25#issuecomment-873497994

**Pull request closed without merging**
