### PR TITLE
Pull in latest Mermaid JS - 8.2.6

### PR DESCRIPTION
**Pull request by simonwfarrow**
Hi,

I have pulled down the latest mermaid release from [here](https://unpkg.com/browse/mermaid@8.2.6/dist/mermaid.js)
This has dropped the CSS files, so I have removed those. 
I have also added a new parameter called mermaidTheme which allows you to set which theme to use as per this [breaking change](https://github.com/knsv/mermaid/blob/343277e387d0b08dbe9ce3fb9d6968d3af8408a3/docs/breakingChanges.md#2)

### CODE REVIEW

**Comment by aazon** [comment]
Are there any reasons not to merge this pull request?

**Comment by mirisbowring** [comment]
@aazon your solution is not best practice in my opinion, because it does not exactly solve the problem (see #361 #362).

**Comment by mbbx6spp** [comment]
See #443 for later upgrade.

**Comment by mirisbowring** [comment]
But why should this implementation be better than the CDN method?
You're must download mermaid from CDN to use it - so even your version is from the mermaid CDN.

In 2-3 Weeks your version is outdated and has to be updated manually via a new PR.

BTW, Git is not made for handling framework's (each upgrade, your repo is growing by some Megabytes) - That is why node was invented (besides many other reasons).

**Comment by matalo33** [comment]
Thank you for the submission, and apologies for not looking at it sooner. This change is now superseded by #443

**Pull request closed without merging**
